name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/test.yml
    
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project/rag-2-backend/rag-2-backend
            git checkout main
            git pull || { echo "Error: git pull failed" >&2; exit 1; }
            cd /home/project
            docker compose up --build -d
            echo "$(date): backend deployed successfully" >> deploy-log.txt 
            docker system prune -f
