name: .NET

on:
  pull_request:
    branches: [ 'dev' ]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore rag-2-backend
      - name: Build
        run: dotnet build --no-restore rag-2-backend
      - name: Test
        run: dotnet test --no-build --verbosity normal rag-2-backend
